---
general:
  buildTool: "mta"
stages:
  Build:
    mavenExecuteStaticCodeChecks: false
    npmExecuteLint: true
  Additional Unit Tests:
    npmExecuteScripts: false
    karmaExecuteTests: false
  Acceptance:
    cloudFoundryDeploy: false
    cfApiEndpoint: "https://api.cf.eu10.hana.ondemand.com"
    cfOrg: "African_Development_Bank_AfDB_DEVS4"
    cfSpace: "AfDB_S4_DEV"
    cfAppName: "testapp"
    cfCredentialsId: "deploy-to-cf"
    uiVeri5ExecuteTests: false
  Release:
    cloudFoundryDeploy: true
    cfApiEndpoint: "https://api.cf.eu10.hana.ondemand.com"
    cfOrg: "African_Development_Bank_AfDB_DEVS4"
    cfSpace: "AfDB_S4_DEV"
    cfAppName: "testapp"
    cfCredentialsId: "deploy-to-cf"
    tmsUpload: true
steps:
  artifactPrepareVersion:
    versioningType: "cloud_noTag"
  npmExecuteLint:
    failOnError: true
  cloudFoundryDeploy:
    mtaDeployParameters: "-f --version-rule ALL"
  tmsUpload:
    nodeName: "qa"
    credentialsId: "tms-sk"
